apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/sound-chimera-457618-d7/locations/europe-west1-c/clusters/cluster-1

